enum InsumoClinicoNamesEnum {
    AguaEsteril_500ml = "Agua esteril x 500 ml",
    Aminoacidos15_1000Ml = "Aminoácidos 15 % x 1000 ml",
    Aminoacidos15_500Ml = "Aminoácidos 15 % x 500 ml",
    AminoacidosConElectrolitos10_500Ml = "Aminoácidos con electrolitos 10% x 500 ml",
    AminoacidosInfantil100Ml = "Aminoácidos infantil x 100 ml",
    AminoacidosInfantil1000Ml = "Aminoácidos infantil x 1000 ml",
    AminoacidosInfantil250Ml = "Aminoácidos infantil x 250 ml",
    AminoacidosInfantil500Ml = "Aminoácidos infantil x 500 ml",
    AminoacidosSinElectrolitos10_500Ml = "Aminoácidos sin electrolitos 10% x 500 ml",
    Bolsa1000Ml = "Bolsa x 1000 ml",
    Bolsa2000Ml = "Bolsa x 2000 ml",
    Bolsa500Ml = "Bolsa x 500 ml",
    CloruroPotasioVial_10cc = "Cloruro de potasio vial x 10cc",
    CloruroSodioVial_10cc = "Cloruro de sodio vial x 10cc",
    Complejo_B = "Complejo B",
    Dextrosa_50p_Bolsa_500cc = "Dextrosa al 50% bolsa x 500cc",
    ElementosTrazaPediatricos10Ml = "Elementos traza pediatricos x 10 ml",
    ElementosTraza10Ml = "Elementos traza x 10 ml",
    FosfatoPotasioVial_10cc = "Fosfato de potasio vial x 10cc",
    GlicerofosfatoSodio20Ml = "Glicerofosfato de sodio x 20 ml",
    GluconatoCalcioVial_10cc = "Gluconato de calcio vial x 10cc",
    LipidosLipofundin100Cc = "Lípidos (lipofundin) frasco vial x 100 cc",
    LipidosLipofundin500Cc = "Lípidos (lipofundin) frasco x 500 cc",
    Multivitaminas = "Multivitaminas",
    MixingEva1000Ml = "Single-chamber mixing container eva 1000 ml",
    MixingEva2000Ml = "Single-chamber mixing container eva 2000 ml",
    MixingEva250Ml = "Single-chamber mixing container eva 250 ml",
    MixingEva500Ml = "Single-chamber mixing container eva 500 ml",
    SulfatoMagnesioVial_10cc = "Sulfato de magnesio vial x 10 cc",
    Tiamina = "Tiamina",
    Vitamina_C = "Vitamina c - acido ascorbico",
    VitaminasHidrosolubles = "Vitaminas hidrosolubles",
    VitaminasLiposolublesAdulto = "Vitaminas liposolubles adulto",
    VitaminasLiposolublesInfantil = "Vitaminas liposolubles infantil"
}

export default InsumoClinicoNamesEnum;